USE [Ahora]
GO
IF EXISTS(SELECT 1 FROM SYS.PROCEDURES WHERE [object_id] = OBJECT_ID('ptl.spDeleteNews'))
	DROP PROCEDURE ptl.spDeleteNews
GO

CREATE PROCEDURE ptl.spDeleteNews
@ID UNIQUEIDENTIFIER,
@RemoverID UNIQUEIDENTIFIER
AS
BEGIN
	--DELETE FROM [ptl].[News] WHERE ID = @ID
	UPDATE ptl.News
	SET
		RemoverID = @RemoverID,
		RemoverDate = GETDATE()
	WHERE
		ID = @ID
	RETURN @@ROWCOUNT
END