USE [Ahora]
GO
IF EXISTS(SELECT 1 FROM SYS.PROCEDURES WHERE [object_id] = OBJECT_ID('ptl.spDeleteSlider'))
	DROP PROCEDURE ptl.spDeleteSlider
GO

CREATE PROCEDURE ptl.spDeleteSlider
@ID UNIQUEIDENTIFIER
AS
BEGIN
	DELETE FROM ptl.Slider
	WHERE
		ID = @ID
	RETURN @@ROWCOUNT
END