USE [Ahora]
GO

IF EXISTS(SELECT 1 FROM sys.procedures WHERE [object_id] = OBJECT_ID('ptl.spDeletePages'))
	DROP PROCEDURE ptl.spDeletePages
GO

CREATE PROCEDURE ptl.spDeletePages
	@ID UNIQUEIDENTIFIER
--WITH ENCRYPTION
AS
BEGIN
	SET XACT_ABORT ON;

	BEGIN TRY
		BEGIN TRAN
		DELETE FROM ptl.DynamicPage WHERE PageID = @ID
		DELETE FROM ptl.Pages
		WHERE ID = @ID
	COMMIT
		RETURN @@ROWCOUNT
	END TRY
	BEGIN CATCH
		;THROW
	END CATCH


END