USE [Ahora]
GO

IF EXISTS(SELECT 1 FROM sys.procedures WHERE [object_id] = OBJECT_ID('pbl.spGetContact'))
	DROP PROCEDURE pbl.spGetContact
GO

CREATE PROCEDURE pbl.spGetContact
@ID UNIQUEIDENTIFIER
--WITH ENCRYPTION
AS
BEGIN
	SET NOCOUNT ON;
	SELECT 
		*
	FROM pbl.Contact
	WHERE ID = @ID
END