USE [Ahora]
GO

IF EXISTS(SELECT 1 FROM sys.procedures WHERE [object_id] = OBJECT_ID('ptl.spDeleteBanner'))
	DROP PROCEDURE ptl.spDeleteBanner
GO

CREATE PROCEDURE ptl.spDeleteBanner
	@ID UNIQUEIDENTIFIER
--WITH ENCRYPTION
AS
BEGIN
	DELETE FROM ptl.Banner
	WHERE ID = @ID
	RETURN @@ROWCOUNT

END